"""
Django settings for EduHub_Learning_Management_API project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Security warning: keep the secret key used in production secret.
SECRET_KEY = 'django-insecure-^)_bx)hp4a_cr@bie(oi*!mn^#hf5+l%1_)u7fdam%83^&bs4a'

# Security warning: do not run with debug turned on in production.
DEBUG = True

ALLOWED_HOSTS = []


# =========================================================
# Application definition
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

    # Required for blacklisting JWT refresh tokens.
    'rest_framework_simplejwt.token_blacklist',

    'accounts',
    'course',
]


# =========================================================
# Django REST Framework
# =========================================================

REST_FRAMEWORK = {
    # Uses JWT tokens to authenticate users in DRF.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


# =========================================================
# Simple JWT Configuration
# =========================================================

SIMPLE_JWT = {
    # Access token will remain valid for 40 minutes.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=40),

    # Refresh token will remain valid for 1 day.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # Generates a new refresh token when the old one is used.
    "ROTATE_REFRESH_TOKENS": True,

    # Blacklists the old refresh token after rotation.
    "BLACKLIST_AFTER_ROTATION": True,

    # Does not automatically update the user's last_login field.
    "UPDATE_LAST_LOGIN": False,
}


# =========================================================
# Custom User Model
# =========================================================

# Uses our custom User model instead of Django's default User model.
AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# Middleware
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL Configuration
# =========================================================

ROOT_URLCONF = 'EduHub_Learning_Management_API.urls'


# =========================================================
# Templates
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'EduHub_Learning_Management_API.wsgi.application'


# =========================================================
# Database
# =========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        # PostgreSQL database name.
        'NAME': 'eduhub_db',

        'USER': 'postgres',
        'PASSWORD': '123',

        # PostgreSQL server host.
        'HOST': 'localhost',

        # Default PostgreSQL port.
        'PORT': '5432'
    }
}


# =========================================================
# Password validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# Static files
# =========================================================

STATIC_URL = 'static/'


# =========================================================
# Default Primary Key
# =========================================================

# Uses BigAutoField as the default primary key for Django models.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# Frontend URL
# =========================================================

# Used to generate the password reset link.
FRONTEND_URL = "https://example.com"


# =========================================================
# Email
# =========================================================

# Console email backend prints emails in the terminal instead
# of sending them to the actual email address.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}